/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import MainScene from "./main/scene/main/MainScene"
import GameUI2 from "./script/GameUI2"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="test/mainScene.scene";
    static battleScene:string = "test/TestScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("main/scene/main/MainScene.ts",MainScene);
        reg("script/GameUI2.ts",GameUI2);
    }
}
GameConfig.init();