export default class SysBullet{
    static NAME:string = 'sys_bullet.txt';
    public id:number = 0;
    public nameTxt:string = '';
    public txt:string = '';
    public bulletCd:number = 0;
    public bulletType:number = 0;
    public bulletMode:number = 0;
    public boomEffect:number = 0;
    public mixNum:number = 0;
    public maxNum:number = 0;
    public bulletAngle:number = 0;
    public bulletNum:number = 0;
    public bulletSpeed:number = 0;
    public bulletBlock:number = 0;
    public bulletEjection:number = 0;
    public ejectionNum:number = 0;
    public bulletsAoe:number = 0;
    public attackAngle:number = 0;
    public bulletSplit:number = 0;
    public splitNum:number = 0;
    public triggerComparison:number = 0;
    public skilltarget:number = 0;
    public callInfo:string = '';
    public damagePercent:number = 0;
    public skillEffect1:number = 0;
    public attackDistance:number = 0;
}